# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20161117_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
