# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
